export const DefaultCategories = [
    "Sleep",
    "School",
    "Other Learning",
    "Exams",
    "Studying",
    "Side Projects",
    "General Productivity",
    "Work",
    "Job Search",
    "Interneting",
    "Friends IRL",
    "Friends Online",
    "Family",
    "Gaming",
    "Eating",
    "Kitchening",
    "Well-being",
    "Shopping",
    "Travel",
    "Dating/Relationships",
    "Wasted Time",
    "Exercise",
    "Events/Competitions",
    "Health",
    "Hobbies"
];
